name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Expose repo slug for star button
        run: echo "NEXT_PUBLIC_GITHUB_REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Validate content
        run: node scripts/validate-content.mjs

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
