name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Expose repo slug for star button
        run: echo "NEXT_PUBLIC_GITHUB_REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Validate content
        run: node scripts/validate-content.mjs

      - name: Lint
        run: npm run lint

      - name: Compute BASE_PATH for Pages
        id: basepath
        run: |
          REPO="${{ github.event.repository.name }}"
          if [[ "$REPO" == *.github.io ]]; then
            echo "BASE_PATH=" >> "$GITHUB_ENV"
            echo "Using root base path (user/org site)"
          else
            echo "BASE_PATH=/$REPO" >> "$GITHUB_ENV"
            echo "Using project base path: /$REPO"
          fi

      - name: Build static site
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: |
          npm run build
          # Ensure ./out exists for upload
          if [ ! -d out ]; then npx next export; fi
          # Disable Jekyll so _next assets are served
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
